//
//  ContentBrain.swift
//  The Tasarım
//
//  Created by Şeyda Soylu on 29.11.2022.
//

import Foundation

var View = [
    Content(image: "https://cdn.dsmcdn.com/ty260/product/media/images/20211129/13/1108436/325162838/1/1_org_zoom.jpg", label: "IKEA Koncıs Paslanmaz Çelik Sarımsak Ezici" ,information: "Ebatlar uzunluk: 16 cm yararlı bilgiler içindeki parça çıkarılarak kolayca temizlenebilir. Sarımsaklar soyulmadan ezilebilir. Bakım talimatları sadece elde yıkanır. Malzeme paslanmaz çelik, çinko, fırça cilalı nikel kaplama." , price: 160, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty234/product/media/images/20211110/14/173591489/302216347/1/1_org_zoom.jpg", label: "IKEA 12 Parça Baharatlık Seti Cam 12liPAKET", information: "Ebatlar: Çap:6.5cm , Yükseklik:8.5cm , Hacim: 15cl , Paket miktarı: 12 adet ,Yararlı bilgiler: Kapak iki farklı yönder açılır. Birinden geniş ağız kısmıyla çok dökülür diğerinden de baharatlık gibi deliklerden az miktarda dökülür. IKEA 365+ IHÄRDIG ile kombine ederek baharatlarınızı doğrudan kavanozdan öğütebilirsiniz. Bakım Talimatları: Bulaşık makinesine girebilir. Malzeme: Cam, Polipropilen plastik ", price: 272, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty96/product/media/images/20210405/08/a35efda3/61246773/1/1_org_zoom.jpg", label: "IKEA Idealısk Paslanmaz Çelik Rende", information: "Ikea ıdealısk paslanmaz çelik rende stoktan ebatlar uzunluk: 12 cm genişlik: 10 cm yükseklik: 20 cm bakım talimatları bulaşık makinesine girebilir. ", price: 115, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty79/product/media/images/20210228/1/67512953/146863881/1/1_org_zoom.jpg", label: "IKEA Frk Koncıs Paslanmaz Çelik Sarımsak Ezici", information: "Ebatlar Uzunluk: 16 cm Yararlı bilgiler İçindeki parça çıkarılarak kolayca temizlenebilir. Sarımsaklar soyulmadan ezilebilir. Bakım talimatları Sadece elde yıkanır. Malzeme Paslanmaz çelik, çinko, fırça cilalı nikel kaplama.", price: 158, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty127/product/media/images/20210608/13/97326697/184655702/1/1_org_zoom.jpg", label: "IKEAKlockren Buharda Sebze Haşlama Ve Pişirici", information: "Ebatlar Yükseklik: 5.5 cm Çap: 24 cm Yararlı Bilgiler Kulp çıkarılarak ısınması engellenir ve tencerenin kolay taşınmasını sağlar. Daha çok 2-5 litrelik ve yanmaz-yapışmaz kaplaması olmayan tencerelerde kullanılır. Bakım Talimatları Bulaşık makinesine girebilir. Malzeme Paslanmaz çelik", price: 150, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty147/product/media/images/20210719/13/111713289/206794269/1/1_org_zoom.jpg", label: "IKEA Lamplig Nihale Paslanmaz Çelik Büyük Boy", information: "Kampanya fiyatından satılmak üzere 5 adetten az stok bulunmaktadır.", price: 197, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty138/product/media/images/20210705/12/107199181/197971298/1/1_org_zoom.jpg", label: "IKEA Heat Nihale Mantar Tava Çaydanlık Altlığı", information: "Ebatlar: Çap: 19 cm , Paket miktarı: 1 Adet , Yararlı bilgiler: Birkaç nihaleyi birleştirilerek büyük tencere ve tabaklar için kullanabilirsiniz. Malzeme: Mantar ", price: 53, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty78/product/media/images/20210301/22/67756059/147160730/1/1_org_zoom.jpg", label: "IKEA İdealist Çırpma Seti 2'li", information: "Malzeme: Paslanmaz çelik. Bakım talimatları: Bulaşık makinesine girebilir.Bilmekte fayda var İçindekiler Çırpıcı 25 cm ve çırpıcı 26 cm 2 adet", price: 83, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty75/product/media/images/20210223/15/66225409/145150913/1/1_org_zoom.jpg", label: "IKEA Korken Kapaklı Kavanoz Cam 3 Adet", information: "Kampanya fiyatından satılmak üzere 5 adetten az stok bulunmaktadır.", price: 135, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty27/product/media/images/20201201/11/34028624/16865914/1/1_org_zoom.jpg", label: "IKEA GREJA Peçetelik", information: "Polipropilen Plastik Peçeteleri Düzenli Tutarak Bir Arada Kalmalarını Sağlar.Nemli bez ile siliniz. Uzunluk: 15cm . Genişlik: 11cm , Yükseklik: 16cm", price: 59, like:"", basket: "") ,
    Content(image: "https://cdn.dsmcdn.com/ty75/product/media/images/20210224/10/66403400/145391832/1/1_org_zoom.jpg", label: "IKEA 365+ Siyah Rende Ve Dilimleme Aparatı", information: "Kampanya fiyatından satılmak üzere 5 adetten az stok bulunmaktadır.", price: 235, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty98/product/media/images/20210405/07/9bb45d86/61205091/1/1_org_zoom.jpg", label: "IKEA Idealisk Ikili Metal Çırpıcı Seti", information: "Ikea ikili metal çırpıcı seti sadece bir çırpma işlemi için mutfak robotunu çıkartıp, işlem bittikten sonra tüm parçaları tek tek yıkamaktan sizde dertli iseniz, biraz kolunuzu çalıştırıp bu pratik aletler ile işinizi kolayca görebilirsiniz.", price: 79, like:"", basket: "") ,
    Content(image: "https://cdn.dsmcdn.com/ty98/product/media/images/20210405/08/9d9a9a90/61307198/1/1_org_zoom.jpg", label: "IKEA Finfördela Esnek Kesme Tahtası - 2 Adet", information: "Kampanya fiyatından satılmak üzere 10 adetten fazla stok sunulmuştur.", price: 75, like:"", basket: "") ,
    Content(image: "https://cdn.dsmcdn.com/ty118/product/media/images/20210526/17/92284462/178860396/1/1_org_zoom.jpg", label: "IKEA Bulaşık Kurutma Örtüsü, Koyu Gri", information: "Uzunluk: 44 cm Genişlik: 36 cm 30 derecede makinede yıkanır, kurutma yapılmaz ve ütülenmez. Kumaş: %100 polyester. Dolgu malzemesi: Poliüretan sünger 25 kg/m3. ", price: 143, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty329/product/media/images/20220209/1/47309299/93481540/1/1_org_zoom.jpg", label: "Decathlon Pongori Ttb100 1* 40 Masa Tenisi Topu", information: "TTB100 BY DECATHLON Masa Tenisi Topu 40+ 6'lı Beyaz Düzenli olarak masa tenisi oynayan ve bir antrenman topu arayanlar için tasarlandı. Selüloit içermeyen ve dayanıklı plastik bir top mu arıyorsunuz? TTB 100 top antrenmanlarınız ve pinpon setleriniz için idealdir. Merhaba Sporsever, Decathlon olarak gezegenimizi seviyoruz. Bunun için fabrikalarımızdan depomuza ve depomuzdan da sana ulaşan ürünlerimizin ambalajında mümkün olduğunca az paketleme yapmaya özen gösteriyoruz. #doğaolmadansporolmaz", price: 60, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty332/product/media/images/20220214/21/50328378/387618813/1/1_org_zoom.jpg", label: "IKEA Mutfak Makası 2'li Takım MARKBART MAKAS", information: "13 VE 20 CM OLARAK 2 Adet bulunmaktadır.", price: 109, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty64/product/media/images/20210202/9/59244154/136882692/1/1_org_zoom.jpg", label: "IKEA Rinnig Vantuzlu Plastik Bulaşık Fırçası", information: "Ebatlar Uzunluk: 29 cm Yararlı Bilgiler Vantuzlar sayesinde eviye ve seramik gibi yüzeylere kolayca yapışır. Spatula kenar, inatçı yiyecek kalıntılarının çıkarılmasını kolaylaştırır. Bakım Talimatları Bulaşık makinesine girebilir. Malzeme Kulp:Polipropilen plastik Fırça:Polyester Vakumlu kap:Sentetik kauçuk.", price: 60, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty144/product/media/images/20210715/11/110816961/203222012/1/1_org_zoom.jpg", label: "IKEA 30 Adet Elbise Askısı(trend My Home) ", information: "İkea Elbise Askısı 30 Adet Ebatlar Genişlik: 39 cm Paket miktarı: 30 adet Yararlı Bilgiler Pantolon askısı, etek askısı ve gömlek askısı bir arada. Malzeme Güçlendirilmiş polipropilen plastik", price: 260, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty96/product/media/images/20210405/07/d51fc4fc/61211071/1/1_org_zoom.jpg", label: "IKEAMedelvag Şişe Kavanoz Bulaşık Temizleme Fırçası", information: "Medelvag şişe temizleme fırçası kargo bedava ebatlaruzunluk: 43 cmyararlı bilgilerfırçanın yumuşak yapısı ve ince sapı sayesinde dar ağızlı şişelerin içini kolayca temizleyebilirsiniz.bakım talimatlarısadece elde yıkanır.malzemeana malzeme:Polipropilen plastiksert kıllar:Poliamid plastiknot: hafta içi 17:00 - Cumartesi 12:00'a kadar verilen siparişler aynı gün kargoya verilir", price: 55, like:"", basket: "") ,
    Content(image: "https://cdn.dsmcdn.com/ty78/product/media/images/20210303/18/68379207/147987022/0/0_org_zoom.jpg", label: "IKEA Kurulama Bezi Beyaz-gri Pamuk 45x60 Cm 4adet", information: "204.763.46 ?Ebatlar Uzunluk: 60 cm Genişlik: 45 cm Paket miktarı: 4 adet Yararlı Bilgiler İplik boyama kumaş yıkandıktan sonra da rengini korur. Asılabilir, kullanılmadığında kolayca saklanabilir. Bilmekte Fayda Var Her havlunun değişik dizaynı vardır. İlk kullanımdan önce ürünü yıkayın. Bakım Talimatları Maksimum çekme payı %4. Makinede yıkanır, maks 60°C, normal program. Çamaşır suyu kullanılmaz. Makinede kurutulur, normal ısı (maks 80°C). Ütülenebilir, maks 200°C. Kuru temizleme yapılmaz. Malzeme %100 pamuk", price: 130, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty207/product/media/images/20211023/21/155407676/272687865/1/1_org_zoom.jpg", label: "IKEA Bevara Paket Poşet Mandalı 30 Adet ", information: "Bulaşık makinesine girebilir.Malzeme polipropilen plastik", price: 70, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty73/product/media/images/20210218/12/64856516/143301216/1/1_org_zoom.jpg", label: "IKEA Storavan Banyo Aksesuar Seti Sabunluk", information: "Storavan banyo aksesuar seti - Sıvı sabunluk - Katı sabunluk - Diş fırçalık - Içindekiler: 1 adet sabunluk 40 cl (yükseklik 16,5 cm), 1 adet diş fırçası tutucu 40 cl (yükseklik 11 cm) 1 adet tepsi (uzunluk 15 cm, derinlik 7,5 cm). Kap/ tepsi:Polipropilen plastik (en az %20'si geri dönüştürülmüştür) pompa:Polietilen plastik, polipropilen plastik (en az %20'si geri dönüştürülmüştür), polipropilen plastik, cam", price: 99, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty223/product/media/images/20211104/18/165687973/288267707/1/1_org_zoom.jpg", label: "IKEA Dekoratif Cam Vazo, 17 Cm", information: "Malzeme: Cam Yükseklik: 17 cm Sadece elde yıkanır.", price: 65, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty15/product/media/images/20201009/21/14642570/61233293/1/1_org_zoom.jpg", label: "IKEA Bastis Kedi Köpek 4 Adet Yedek Tüy Toplama Rulosu", information: "Ikea Bastis Tüy Toplayıcı Yedek 4'Lü Hayvan tüylerini, mobilya, giysi ve araba koltuklarından gelen toz ve tüyleri kolayca ve hızlı bir şekilde temizler.60 yapraktan oluşur.9 m uzunluğundadır.", price: 129, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty157/product/media/images/20210810/11/117286467/225202031/1/1_org_zoom.jpg", label: "IKEA Fantastisk Açık Yeşil Peçete 40x40 cm 50 Adet", information: "Kampanya fiyatından satılmak üzere 5 adetten az stok bulunmaktadır.", price: 64, like:"", basket: ""),
    Content(image: "https://cdn.dsmcdn.com/ty94/product/media/images/20210405/07/bd7d2f0e/61205538/1/1_org_zoom.jpg", label: "IKEA Sarı Mutfak Makası 16 cm", information: "Ikea kvalıfıcera mutfak makası 16 cm sarı renk ebatlar uzunluk: 16 cm yararlı bilgiler hem sağlak, hem de solaklar için tasarlanmıştır.Bakım talimatları bulaşık makinesine girebilir.Malzeme paslanmaz çelik, güçlendirilmiş polipropilen plastik", price: 50, like:"", basket: "")
]
